name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env: 
      TURBO_SECRET: ${{ secrets.TURBO_SECRET }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build the project
        run: pnpm run build
      - name: Run tests
        run: pnpm run test